/** =======================================================================
 * buzzer/songs/astronomia/astronomia.c
 *
 * Define values for the Astronomia / Coffins Dance song.
 *
 * l.heywang
 * 05 / 03 / 2025
 *  =======================================================================
 */

/** =======================================================================
 *	LIBS
 *  =======================================================================
 */
// Header
#include "astronomia.h"

// Libs
#include "../../note.h"
#include "../songs.h"

/** =======================================================================
 *	DATA
 *  =======================================================================
 */

const int astronomia_data[] = {
		// Line 1
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),

		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),

		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4),

		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Do4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Do4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Do4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Do4),

		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4_d),

		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),

		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Do4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa3),

		_REG_FROM_PARAM(50, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Do4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La3),
		_REG_FROM_PARAM(50, DEFAULT_VOLUME, Do4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La3),

		_REG_FROM_PARAM(50, DEFAULT_VOLUME, Sol3_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol4_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol4_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La4),

		_REG_FROM_PARAM(50, DEFAULT_VOLUME, Sol3_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol4_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol4_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La4),

		_REG_FROM_PARAM(50, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Do4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La3),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La3),
		_REG_FROM_PARAM(50, DEFAULT_VOLUME, Do4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La3),

		_REG_FROM_PARAM(50, DEFAULT_VOLUME, Sol3_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol4_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol4_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La4),

		_REG_FROM_PARAM(50, DEFAULT_VOLUME, Sol3_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol3_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol4_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Sol4_d),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, La4),

		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Si3_b),

		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Re4),

		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Do4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Do4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Do4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Do4),

		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
		_REG_FROM_PARAM(25, DEFAULT_VOLUME, Fa4),
};

const struct song Astronomia = {
	.name = "Astronomia",
	.artist = "?",
	.len = (sizeof(astronomia_data) / sizeof(int)),
	.notes = astronomia_data
};
