/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'NiosII_CPU' in SOPC Builder design 'QsysTD'
 * SOPC Builder design path: ../../QsysTD.sopcinfo
 *
 * Generated: Sat Apr 05 17:01:27 CEST 2025
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * BOUTONS_POUSSOIRS configuration
 *
 */

#define ALT_MODULE_CLASS_BOUTONS_POUSSOIRS altera_avalon_pio
#define BOUTONS_POUSSOIRS_BASE 0x41080
#define BOUTONS_POUSSOIRS_BIT_CLEARING_EDGE_REGISTER 0
#define BOUTONS_POUSSOIRS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BOUTONS_POUSSOIRS_CAPTURE 1
#define BOUTONS_POUSSOIRS_DATA_WIDTH 2
#define BOUTONS_POUSSOIRS_DO_TEST_BENCH_WIRING 0
#define BOUTONS_POUSSOIRS_DRIVEN_SIM_VALUE 0
#define BOUTONS_POUSSOIRS_EDGE_TYPE "FALLING"
#define BOUTONS_POUSSOIRS_FREQ 50000000
#define BOUTONS_POUSSOIRS_HAS_IN 1
#define BOUTONS_POUSSOIRS_HAS_OUT 0
#define BOUTONS_POUSSOIRS_HAS_TRI 0
#define BOUTONS_POUSSOIRS_IRQ 4
#define BOUTONS_POUSSOIRS_IRQ_INTERRUPT_CONTROLLER_ID 0
#define BOUTONS_POUSSOIRS_IRQ_TYPE "EDGE"
#define BOUTONS_POUSSOIRS_NAME "/dev/BOUTONS_POUSSOIRS"
#define BOUTONS_POUSSOIRS_RESET_VALUE 0
#define BOUTONS_POUSSOIRS_SPAN 16
#define BOUTONS_POUSSOIRS_TYPE "altera_avalon_pio"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00040820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x13
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00020020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 2048
#define ALT_CPU_INST_ADDR_WIDTH 0x13
#define ALT_CPU_NAME "NiosII_CPU"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00020000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00040820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x13
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00020020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 2048
#define NIOS2_INST_ADDR_WIDTH 0x13
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00020000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_NIOS2_GEN2


/*
 * HEX3_HEX0 configuration
 *
 */

#define ALT_MODULE_CLASS_HEX3_HEX0 altera_avalon_pio
#define HEX3_HEX0_BASE 0x410b0
#define HEX3_HEX0_BIT_CLEARING_EDGE_REGISTER 0
#define HEX3_HEX0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEX3_HEX0_CAPTURE 0
#define HEX3_HEX0_DATA_WIDTH 32
#define HEX3_HEX0_DO_TEST_BENCH_WIRING 0
#define HEX3_HEX0_DRIVEN_SIM_VALUE 0
#define HEX3_HEX0_EDGE_TYPE "NONE"
#define HEX3_HEX0_FREQ 50000000
#define HEX3_HEX0_HAS_IN 0
#define HEX3_HEX0_HAS_OUT 1
#define HEX3_HEX0_HAS_TRI 0
#define HEX3_HEX0_IRQ -1
#define HEX3_HEX0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define HEX3_HEX0_IRQ_TYPE "NONE"
#define HEX3_HEX0_NAME "/dev/HEX3_HEX0"
#define HEX3_HEX0_RESET_VALUE -1
#define HEX3_HEX0_SPAN 16
#define HEX3_HEX0_TYPE "altera_avalon_pio"


/*
 * HEX5_HEX4 configuration
 *
 */

#define ALT_MODULE_CLASS_HEX5_HEX4 altera_avalon_pio
#define HEX5_HEX4_BASE 0x410a0
#define HEX5_HEX4_BIT_CLEARING_EDGE_REGISTER 0
#define HEX5_HEX4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEX5_HEX4_CAPTURE 0
#define HEX5_HEX4_DATA_WIDTH 32
#define HEX5_HEX4_DO_TEST_BENCH_WIRING 0
#define HEX5_HEX4_DRIVEN_SIM_VALUE 0
#define HEX5_HEX4_EDGE_TYPE "NONE"
#define HEX5_HEX4_FREQ 50000000
#define HEX5_HEX4_HAS_IN 0
#define HEX5_HEX4_HAS_OUT 1
#define HEX5_HEX4_HAS_TRI 0
#define HEX5_HEX4_IRQ -1
#define HEX5_HEX4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define HEX5_HEX4_IRQ_TYPE "NONE"
#define HEX5_HEX4_NAME "/dev/HEX5_HEX4"
#define HEX5_HEX4_RESET_VALUE -1
#define HEX5_HEX4_SPAN 16
#define HEX5_HEX4_TYPE "altera_avalon_pio"


/*
 * INTERRUPTEURS configuration
 *
 */

#define ALT_MODULE_CLASS_INTERRUPTEURS altera_avalon_pio
#define INTERRUPTEURS_BASE 0x410c0
#define INTERRUPTEURS_BIT_CLEARING_EDGE_REGISTER 0
#define INTERRUPTEURS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define INTERRUPTEURS_CAPTURE 0
#define INTERRUPTEURS_DATA_WIDTH 10
#define INTERRUPTEURS_DO_TEST_BENCH_WIRING 0
#define INTERRUPTEURS_DRIVEN_SIM_VALUE 0
#define INTERRUPTEURS_EDGE_TYPE "NONE"
#define INTERRUPTEURS_FREQ 50000000
#define INTERRUPTEURS_HAS_IN 1
#define INTERRUPTEURS_HAS_OUT 0
#define INTERRUPTEURS_HAS_TRI 0
#define INTERRUPTEURS_IRQ -1
#define INTERRUPTEURS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define INTERRUPTEURS_IRQ_TYPE "NONE"
#define INTERRUPTEURS_NAME "/dev/INTERRUPTEURS"
#define INTERRUPTEURS_RESET_VALUE 0
#define INTERRUPTEURS_SPAN 16
#define INTERRUPTEURS_TYPE "altera_avalon_pio"


/*
 * LEDR configuration
 *
 */

#define ALT_MODULE_CLASS_LEDR altera_avalon_pio
#define LEDR_BASE 0x41060
#define LEDR_BIT_CLEARING_EDGE_REGISTER 0
#define LEDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDR_CAPTURE 0
#define LEDR_DATA_WIDTH 10
#define LEDR_DO_TEST_BENCH_WIRING 0
#define LEDR_DRIVEN_SIM_VALUE 0
#define LEDR_EDGE_TYPE "NONE"
#define LEDR_FREQ 50000000
#define LEDR_HAS_IN 0
#define LEDR_HAS_OUT 1
#define LEDR_HAS_TRI 0
#define LEDR_IRQ -1
#define LEDR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDR_IRQ_TYPE "NONE"
#define LEDR_NAME "/dev/LEDR"
#define LEDR_RESET_VALUE 1023
#define LEDR_SPAN 16
#define LEDR_TYPE "altera_avalon_pio"


/*
 * MEMOIRE_ONCHIP configuration
 *
 */

#define ALT_MODULE_CLASS_MEMOIRE_ONCHIP altera_avalon_onchip_memory2
#define MEMOIRE_ONCHIP_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define MEMOIRE_ONCHIP_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define MEMOIRE_ONCHIP_BASE 0x20000
#define MEMOIRE_ONCHIP_CONTENTS_INFO ""
#define MEMOIRE_ONCHIP_DUAL_PORT 0
#define MEMOIRE_ONCHIP_GUI_RAM_BLOCK_TYPE "AUTO"
#define MEMOIRE_ONCHIP_INIT_CONTENTS_FILE "QsysTD_MEMOIRE_ONCHIP"
#define MEMOIRE_ONCHIP_INIT_MEM_CONTENT 0
#define MEMOIRE_ONCHIP_INSTANCE_ID "NONE"
#define MEMOIRE_ONCHIP_IRQ -1
#define MEMOIRE_ONCHIP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MEMOIRE_ONCHIP_NAME "/dev/MEMOIRE_ONCHIP"
#define MEMOIRE_ONCHIP_NON_DEFAULT_INIT_FILE_ENABLED 0
#define MEMOIRE_ONCHIP_RAM_BLOCK_TYPE "AUTO"
#define MEMOIRE_ONCHIP_READ_DURING_WRITE_MODE "DONT_CARE"
#define MEMOIRE_ONCHIP_SINGLE_CLOCK_OP 0
#define MEMOIRE_ONCHIP_SIZE_MULTIPLE 1
#define MEMOIRE_ONCHIP_SIZE_VALUE 122880
#define MEMOIRE_ONCHIP_SPAN 122880
#define MEMOIRE_ONCHIP_TYPE "altera_avalon_onchip_memory2"
#define MEMOIRE_ONCHIP_WRITABLE 1


/*
 * PWM_CTRL configuration
 *
 */

#define ALT_MODULE_CLASS_PWM_CTRL altera_avalon_pio
#define PWM_CTRL_BASE 0x41090
#define PWM_CTRL_BIT_CLEARING_EDGE_REGISTER 0
#define PWM_CTRL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PWM_CTRL_CAPTURE 0
#define PWM_CTRL_DATA_WIDTH 32
#define PWM_CTRL_DO_TEST_BENCH_WIRING 0
#define PWM_CTRL_DRIVEN_SIM_VALUE 0
#define PWM_CTRL_EDGE_TYPE "NONE"
#define PWM_CTRL_FREQ 50000000
#define PWM_CTRL_HAS_IN 0
#define PWM_CTRL_HAS_OUT 1
#define PWM_CTRL_HAS_TRI 0
#define PWM_CTRL_IRQ -1
#define PWM_CTRL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PWM_CTRL_IRQ_TYPE "NONE"
#define PWM_CTRL_NAME "/dev/PWM_CTRL"
#define PWM_CTRL_RESET_VALUE 0
#define PWM_CTRL_SPAN 16
#define PWM_CTRL_TYPE "altera_avalon_pio"


/*
 * PWM_STATUS configuration
 *
 */

#define ALT_MODULE_CLASS_PWM_STATUS altera_avalon_pio
#define PWM_STATUS_BASE 0x41070
#define PWM_STATUS_BIT_CLEARING_EDGE_REGISTER 0
#define PWM_STATUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PWM_STATUS_CAPTURE 1
#define PWM_STATUS_DATA_WIDTH 8
#define PWM_STATUS_DO_TEST_BENCH_WIRING 0
#define PWM_STATUS_DRIVEN_SIM_VALUE 0
#define PWM_STATUS_EDGE_TYPE "RISING"
#define PWM_STATUS_FREQ 50000000
#define PWM_STATUS_HAS_IN 1
#define PWM_STATUS_HAS_OUT 0
#define PWM_STATUS_HAS_TRI 0
#define PWM_STATUS_IRQ 5
#define PWM_STATUS_IRQ_INTERRUPT_CONTROLLER_ID 0
#define PWM_STATUS_IRQ_TYPE "EDGE"
#define PWM_STATUS_NAME "/dev/PWM_STATUS"
#define PWM_STATUS_RESET_VALUE 0
#define PWM_STATUS_SPAN 16
#define PWM_STATUS_TYPE "altera_avalon_pio"


/*
 * SYS_CLK_timer configuration
 *
 */

#define ALT_MODULE_CLASS_SYS_CLK_timer altera_avalon_timer
#define SYS_CLK_TIMER_ALWAYS_RUN 0
#define SYS_CLK_TIMER_BASE 0x41040
#define SYS_CLK_TIMER_COUNTER_SIZE 32
#define SYS_CLK_TIMER_FIXED_PERIOD 0
#define SYS_CLK_TIMER_FREQ 50000000
#define SYS_CLK_TIMER_IRQ 1
#define SYS_CLK_TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SYS_CLK_TIMER_LOAD_VALUE 49999
#define SYS_CLK_TIMER_MULT 0.001
#define SYS_CLK_TIMER_NAME "/dev/SYS_CLK_timer"
#define SYS_CLK_TIMER_PERIOD 1
#define SYS_CLK_TIMER_PERIOD_UNITS "ms"
#define SYS_CLK_TIMER_RESET_OUTPUT 0
#define SYS_CLK_TIMER_SNAPSHOT 1
#define SYS_CLK_TIMER_SPAN 32
#define SYS_CLK_TIMER_TICKS_PER_SEC 1000
#define SYS_CLK_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define SYS_CLK_TIMER_TYPE "altera_avalon_timer"


/*
 * SYS_MEL configuration
 *
 */

#define ALT_MODULE_CLASS_SYS_MEL altera_avalon_timer
#define SYS_MEL_ALWAYS_RUN 0
#define SYS_MEL_BASE 0x41000
#define SYS_MEL_COUNTER_SIZE 32
#define SYS_MEL_FIXED_PERIOD 0
#define SYS_MEL_FREQ 50000000
#define SYS_MEL_IRQ 3
#define SYS_MEL_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SYS_MEL_LOAD_VALUE 3124999
#define SYS_MEL_MULT 0.001
#define SYS_MEL_NAME "/dev/SYS_MEL"
#define SYS_MEL_PERIOD 62.5
#define SYS_MEL_PERIOD_UNITS "ms"
#define SYS_MEL_RESET_OUTPUT 0
#define SYS_MEL_SNAPSHOT 1
#define SYS_MEL_SPAN 32
#define SYS_MEL_TICKS_PER_SEC 16
#define SYS_MEL_TIMEOUT_PULSE_OUTPUT 0
#define SYS_MEL_TYPE "altera_avalon_timer"


/*
 * SYS_SEC configuration
 *
 */

#define ALT_MODULE_CLASS_SYS_SEC altera_avalon_timer
#define SYS_SEC_ALWAYS_RUN 0
#define SYS_SEC_BASE 0x41020
#define SYS_SEC_COUNTER_SIZE 32
#define SYS_SEC_FIXED_PERIOD 0
#define SYS_SEC_FREQ 50000000
#define SYS_SEC_IRQ 2
#define SYS_SEC_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SYS_SEC_LOAD_VALUE 49999999
#define SYS_SEC_MULT 1.0
#define SYS_SEC_NAME "/dev/SYS_SEC"
#define SYS_SEC_PERIOD 1
#define SYS_SEC_PERIOD_UNITS "s"
#define SYS_SEC_RESET_OUTPUT 0
#define SYS_SEC_SNAPSHOT 1
#define SYS_SEC_SPAN 32
#define SYS_SEC_TICKS_PER_SEC 1
#define SYS_SEC_TIMEOUT_PULSE_OUTPUT 0
#define SYS_SEC_TYPE "altera_avalon_timer"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "MAX 10"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x410d8
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x410d8
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x410d8
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "QsysTD"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK SYS_CLK_TIMER
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x410d8
#define JTAG_UART_0_IRQ 0
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * sysid_qsys_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_qsys_0 altera_avalon_sysid_qsys
#define SYSID_QSYS_0_BASE 0x410d0
#define SYSID_QSYS_0_ID 305419896
#define SYSID_QSYS_0_IRQ -1
#define SYSID_QSYS_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_QSYS_0_NAME "/dev/sysid_qsys_0"
#define SYSID_QSYS_0_SPAN 8
#define SYSID_QSYS_0_TIMESTAMP 1743864783
#define SYSID_QSYS_0_TYPE "altera_avalon_sysid_qsys"

#endif /* __SYSTEM_H_ */
